---
name: Lint
on:
  pull_request:
    branches: [hello-kind]
  push:
    branches: [hello-kind]

jobs:
  check-renovate-config-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: konflux-ci/renovate-config-validator-action@078d8d5e483879bcb260de0f717be30b59df010c  # main
        with:
          config_file: .github/renovate.json
