---
name: Lint
on:
  pull_request:
    branches: [hello-kind]
  push:
    branches: [hello-kind]

jobs:
  check-renovate-config-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: konflux-ci/renovate-config-validator-action@078d8d5e483879bcb260de0f717be30b59df010c  # main
        with:
          config_file: .github/renovate.json
